In [1]:
import pandas as pd
df =pd.read_csv("../docs/sample_500.csv")
df.head(10)

,code,product_name,brands,categories_tags,quantity,product_quantity,product_quantity_unit,serving_size,labels_tags,countries_tags,last_editor,last_modified_t,n_nutrition_sets,set_source,set_per,energy-kcal,fat,sugars,proteins,salt
0,4070308124827,Protein tyčinka,NaN,NaN,40g,40.0,g,NaN,NaN,en:montenegro,ai-food-coach-app,1790836248,1,packaging,100g,292.4,20.0,18.00,2.1,NaN
1,40466101,Milram 3-Zwiebel-Quark,Milram,"en:dairies, en:fermented-foods, en:fermented-m...",185 g,185.0,g,NaN,"en:no-gluten, en:no-colorings, en:no-preservat...",en:germany,shaky76,1790836231,2,packaging,100g,129.0,8.7,3.80,8.3,1.10
2,5999863467097,NaN,NaN,"en:meals, en:pizzas-pies-and-quiches, en:refri...",NaN,NaN,NaN,NaN,NaN,en:hungary,mistiquen,1790836217,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4045500260918,Land-Buttermilch Zitrone,frischli,NaN,NaN,NaN,NaN,NaN,NaN,en:netherlands,kefirschweiz,1790836187,1,packaging,100g,61.0,0.5,11.00,3.1,0.17
4,3700009286753,La brioche cacao noissette,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:france,kiliweb,1790836121,1,packaging,100g,385.0,17.0,17.00,8.1,0.89
5,8801062628773,NaN,Lotte,NaN,NaN,NaN,NaN,NaN,NaN,en:south-korea,municorn-calorie-counter-app,1790836112,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,8410199021045,Doritos tex-mex,Doritos,"en:snacks, en:salty-snacks, en:appetizers, en:...",140g,140.0,g,30 g,it:RO070065,"en:european-union, en:spain",foodless,1790836027,3,packaging,100g,480.0,22.0,3.70,6.8,0.89
7,8445292390569,smarties minis,Nestlé,NaN,NaN,NaN,NaN,16.4g,NaN,en:united-states,municorn-calorie-counter-app,1790835997,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8693323348113,nazar,nazar,NaN,NaN,NaN,NaN,NaN,NaN,en:belgium,kiliweb,1790835967,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,7394101102002,Västkustsallad,Prinsens,NaN,NaN,NaN,NaN,NaN,NaN,en:sweden,macrofactor,1790835923,1,packaging,100g,407.0,42.1,0.99,3.8,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   code                   500 non-null    object
 1   product_name           460 non-null    object
 2   brands                 403 non-null    object
 3   categories_tags        228 non-null    object
 4   quantity               234 non-null    object
 5   product_quantity       216 non-null    float64
 6   product_quantity_unit  216 non-null    object
 7   serving_size           256 non-null    object
 8   labels_tags            149 non-null    object
 9   countries_tags         499 non-null    object
 10  last_editor            496 non-null    object
 11  last_modified_t        500 non-null    int64
 12  n_nutrition_sets       500 non-null    int64
 13  set_source             325 non-null    object
 14  set_per                325 non-null    object
 15  energy-kcal            272 non-null    float64
 16  fat                    251 non-null    float64
 17  sugars                 226 non-null    float64
 18  proteins               251 non-null    float64
 19  salt                   155 non-null    float64
dtypes: float64(6), int64(2), object(12)
memory usage: 78.3+ KB

In [3]:
df.describe()

,product_quantity,last_modified_t,n_nutrition_sets,energy-kcal,fat,sugars,proteins,salt
count,216.000000,5.000000e+02,500.000000,272.000000,251.000000,226.000000,251.000000,155.000000
mean,368.921487,1.790831e+09,1.350000,257.807129,12.268784,9.550396,9.168785,6.094222
std,367.404946,3.285358e+03,0.925859,174.584210,15.144120,13.745100,8.373327,58.253697
min,20.000000,1.790825e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,160.000000,1.790828e+09,1.000000,95.178571,1.200000,1.725000,3.300000,0.100000
50%,250.000000,1.790831e+09,1.000000,252.012311,7.500000,3.565000,7.900000,0.580000
75%,500.000000,1.790833e+09,2.000000,375.000000,18.750000,11.000000,12.034483,1.287500
max,2000.000000,1.790836e+09,4.000000,851.577440,94.100000,76.000000,66.666000,720.000000

In [5]:
#count values in a text column
df["product_quantity_unit"].value_counts()

product_quantity_unit
g     176
ml     40
Name: count, dtype: int64

In [6]:
df["set_source"].value_counts()

set_source
packaging       264
estimate         58
manufacturer      3
Name: count, dtype: int64